version: "3.7"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - STREAMLIT_SERVER_PORT=8001
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      - FASTAPI_SERVER_PORT=8002
      - TOKEN=/run/secrets/tinkoff-token
    ports:
      - "8002:8002"
    secrets:
      - tinkoff-token


secrets:
  tinkoff-token:
    file: ./secrets/tinkoff_token.txt
